/* ODDS SCOPE — real-time 3D race visualization. Generic horse models and schematic course; not actual footage. */
(function(){'use strict';
const PALETTE=[0xf3f3eb,0x171d27,0xd9293e,0x235db8,0xf4cc2f,0x128552,0xe76823,0xdb76a2];
let halos=[],haloTexture;
let skyKey='',atmosphere='day',moodOverride=null,hemi,sun,glowMaterial;
let gate,gateKey="",lastRaceKey=null,doors=[],gateSpan=14;
let T,scene,camera,renderer,host,canvas,world,herd,models=[],labels,ui,sourceKey='',courseKey='',raf=0,lastPaint='',mode=0,direction=1,directionOverride=null,ready=false,loading=false,disposed=false;
const L=48,R=27,PERIMETER=4*L+2*Math.PI*R,FINISH=L*1.5,FINISH_AT=.94,TRAVEL=(PERIMETER-(2*L+Math.PI*R+20)+FINISH)/FINISH_AT,START=FINISH-FINISH_AT*TRAVEL;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mats=new Map(),geo={};
function mat(color,roughness=.7,metalness=0){const key=[color,roughness,metalness].join(':');if(!mats.has(key))mats.set(key,new T.MeshStandardMaterial({color,roughness,metalness}));return mats.get(key)}
function ell(parent,x,y,z,sx,sy,sz,m,shadow=true){const mesh=new T.Mesh(geo.sphere,m);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=shadow;parent.add(mesh);return mesh}
function block(parent,x,y,z,sx,sy,sz,m,shadow=false){const mesh=new T.Mesh(geo.box,m);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=shadow;mesh.receiveShadow=true;parent.add(mesh);return mesh}
function rod(parent,a,b,r,m,r2=r){const av=new T.Vector3(...a),bv=new T.Vector3(...b),len=av.distanceTo(bv);const mesh=new T.Mesh(new T.CylinderGeometry(r2,r,len,7),m);mesh.position.copy(av.add(bv).multiplyScalar(.5));mesh.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),new T.Vector3(...b).sub(new T.Vector3(...a)).normalize());parent.add(mesh);return mesh}
function curve(parent,points,r,m){const mesh=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p))),18,r,5,false),m);parent.add(mesh);return mesh}
function contour(parent,rings,m){const vertices=[],indices=[],N=18;for(let j=0;j<rings.length;j++){const [x,y,ry,rz]=rings[j];for(let k=0;k<=N;k++){const a=k/N*Math.PI*2;vertices.push(x,y+Math.cos(a)*ry,Math.sin(a)*rz)}}for(let j=0;j<rings.length-1;j++)for(let k=0;k<N;k++){const a=j*(N+1)+k,b=a+N+1;indices.push(a,b,a+1,b,b+1,a+1)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setIndex(indices);g.computeVertexNormals();const mesh=new T.Mesh(g,m);mesh.castShadow=true;parent.add(mesh);return mesh}
function batchChildren(parent){
 const groups=new Map();for(const o of [...parent.children])if(o.isMesh&&!Array.isArray(o.material)){const key=o.material.uuid+':'+o.castShadow+':'+o.receiveShadow;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(o)}
 for(const list of groups.values()){if(list.length<2)continue;const pos=[],norm=[],uv=[],idx=[];let offset=0;for(const o of list){o.updateMatrix();const g=o.geometry,pa=g.attributes.position,na=g.attributes.normal,ua=g.attributes.uv,nm=new T.Matrix3().getNormalMatrix(o.matrix);for(let i=0;i<pa.count;i++){const v=new T.Vector3().fromBufferAttribute(pa,i).applyMatrix4(o.matrix);pos.push(v.x,v.y,v.z);const n=na?new T.Vector3().fromBufferAttribute(na,i).applyMatrix3(nm).normalize():new T.Vector3(0,1,0);norm.push(n.x,n.y,n.z);uv.push(ua?ua.getX(i):0,ua?ua.getY(i):0)}if(g.index){for(let i=0;i<g.index.count;i++)idx.push(g.index.getX(i)+offset)}else for(let i=0;i<pa.count;i++)idx.push(i+offset);offset+=pa.count;parent.remove(o);if(!Object.values(geo).includes(g))g.dispose()}
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('normal',new T.Float32BufferAttribute(norm,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);const mesh=new T.Mesh(g,list[0].material);mesh.castShadow=list[0].castShadow;mesh.receiveShadow=list[0].receiveShadow;parent.add(mesh)}
}
function horse(h,index){
 const root=new T.Group(),body=new T.Group();root.add(body);const coats=[0x4d2415,0x231c18,0x774225,0x38281f,0x9c7454,0xaba79d],coat=mat(coats[index%coats.length],.46),muscle=mat(new T.Color(coats[index%coats.length]).multiplyScalar(.91).getHex(),.5),black=mat(0x181619,.88),leather=mat(0x201712,.48),skin=mat(0xc59068,.8),silk=mat(PALETTE[clamp((+h.frame||1)-1,0,7)],.4),white=mat(0xe8e5d9,.72);
 // Sculpted barrel, shoulders, haunches, rising neck and tapered head.
 contour(body,[[-.79,1.19,.02,.03],[-.64,1.25,.24,.26],[-.44,1.28,.31,.31],[-.05,1.28,.28,.28],[.32,1.31,.32,.27],[.51,1.37,.20,.20],[.58,1.43,.03,.04]],coat);
 for(const side of [-1,1]){ell(body,-.49,1.19,side*.2,.25,.33,.17,muscle);ell(body,.36,1.24,side*.16,.22,.34,.17,coat)}
 const neck=ell(body,.53,1.61,0,.23,.46,.20,coat);neck.rotation.z=-.42;const crest=ell(body,.55,1.73,0,.15,.37,.135,coat);crest.rotation.z=-.35;
 contour(body,[[.67,1.96,.05,.06],[.76,1.99,.17,.145],[.94,1.96,.14,.115],[1.15,1.83,.10,.085],[1.27,1.79,.075,.08],[1.31,1.79,.01,.02]],coat);
 ell(body,1.22,1.78,0,.115,.075,.093,muscle);
 for(const side of [-1,1]){const ear=ell(body,.75,2.18,side*.095,.035,.14,.045,coat);ear.rotation.z=.15;ell(body,.77,2.2,side*.098,.018,.09,.025,black,false);ell(body,.9,2.013,side*.12,.033,.022,.014,black,false);ell(body,.91,2.02,side*.13,.009,.007,.005,white,false);ell(body,1.22,1.82,side*.084,.034,.018,.011,black,false)}
 // Mane, tail, tack and reins are actual geometry.
 for(let j=0;j<8;j++){const m=ell(body,.40+j*.043,1.48+j*.071,-.007,.072,.10,.027,black,false);m.rotation.z=-.65}
 const tail=new T.Group();tail.position.set(-.73,1.36,0);body.add(tail);curve(tail,[[0,0,0],[-.25,-.12,0],[-.50,-.28,.02],[-.72,-.36,.03]],.055,black);curve(tail,[[-.15,-.04,.03],[-.46,-.12,.05],[-.67,-.20,.08]],.025,black);
 for(const side of [-1,1]){const number=new T.Mesh(new T.PlaneGeometry(.48,.35),new T.MeshBasicMaterial({map:labelTexture(String(h.horse),'#101c21','#ffffff'),side:T.DoubleSide}));number.position.set(-.09,1.31,side*.327);number.rotation.y=side<0?Math.PI:0;body.add(number)}
 const cloth=ell(body,-.08,1.51,0,.33,.065,.34,silk);block(body,-.10,1.55,0,.40,.055,.31,leather);
 for(const side of [-1,1]){curve(body,[[.70,2.09,side*.12],[.82,1.96,side*.16],[1.19,1.77,side*.10]],.014,leather);curve(body,[[1.20,1.79,side*.09],[.74,1.64,side*.22],[.37,1.78,side*.23]],.009,leather);rod(body,[-.05,1.5,side*.29],[-.05,1.02,side*.27],.025,leather)}
 const legs=[];
 for(const x of [-.48,.38])for(const side of [-1,1]){const upper=new T.Group();upper.position.set(x,1.13,side*.20);body.add(upper);const hind=x<0;ell(upper,0,-.16,0,hind?.115:.09,.22,.085,coat);rod(upper,[0,-.15,0],[.02,-.43,0],.051,coat,.073);const knee=new T.Group();knee.position.set(.02,-.43,0);upper.add(knee);ell(knee,0,0,0,.065,.066,.061,muscle);rod(knee,[0,0,0],[0,-.40,0],.032,coat,.042);ell(knee,0,-.34,0,.045,.07,.044,coat);const hoof=ell(knee,.025,-.47,0,.084,.055,.068,black);legs.push({upper,knee,hind,side})}
 // Jockey in a racing crouch, with bent knees and elbows.
 const rider=new T.Group();rider.position.set(-.17,1.58,0);body.add(rider);const torso=ell(rider,.22,.23,0,.15,.29,.14,silk);torso.rotation.z=-1.04;ell(rider,.46,.38,0,.091,.10,.085,skin);ell(rider,.45,.46,0,.125,.078,.11,silk);block(rider,.54,.43,0,.105,.018,.13,black);block(rider,.53,.385,0,.027,.032,.17,black);
 for(const side of [-1,1]){rod(rider,[-.01,.08,side*.12],[.2,-.13,side*.27],.071,white);rod(rider,[.2,-.13,side*.27],[-.07,-.41,side*.30],.048,black);ell(rider,-.02,-.43,side*.30,.12,.044,.057,black);rod(rider,[.36,.28,side*.13],[.27,.09,side*.23],.043,silk);rod(rider,[.27,.09,side*.23],[.52,.09,side*.22],.032,skin);ell(rider,.54,.10,side*.22,.042,.04,.033,white)}
 const ring=new T.Mesh(new T.RingGeometry(.82,.88,40),new T.MeshBasicMaterial({color:0xffd16e,transparent:true,opacity:.85,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.025;root.add(ring);
 const label=document.createElement('button');label.type='button';label.className='r3-label';label.textContent=String(h.horse);label.setAttribute('aria-label',h.horse+'番 '+(h.name||''));label.style.background='#'+PALETTE[clamp((+h.frame||1)-1,0,7)].toString(16).padStart(6,'0');label.style.color=[1,5].includes(+h.frame)?'#101822':'#fff';label.onclick=()=>{if(typeof window.flowSelectHorse==='function')window.flowSelectHorse(+h.horse)};labels.appendChild(label);
 batchChildren(body);batchChildren(rider);batchChildren(tail);legs.forEach(l=>{batchChildren(l.upper);batchChildren(l.knee)});
 root.userData={h,index,legs,body,rider,tail,ring,label,distance:0};herd.add(root);models.push(root);
}
function pathAt(s,lane=0){s=((s%PERIMETER)+PERIMETER)%PERIMETER;let x,z,tx,tz;if(s<2*L){x=-L+s;z=R;tx=1;tz=0}else if(s<2*L+Math.PI*R){const a=Math.PI/2-(s-2*L)/R;x=L+R*Math.cos(a);z=R*Math.sin(a);tx=Math.sin(a);tz=-Math.cos(a)}else if(s<4*L+Math.PI*R){x=L-(s-2*L-Math.PI*R);z=-R;tx=-1;tz=0}else{const a=-Math.PI/2-(s-4*L-Math.PI*R)/R;x=-L+R*Math.cos(a);z=R*Math.sin(a);tx=Math.sin(a);tz=-Math.cos(a)}return {x:x-tz*lane,z:(z+tx*lane)*direction,tx,tz:tz*direction}}
function trackRibbon(inner,outer,m){const vertices=[],uvs=[],indices=[],steps=380;for(let i=0;i<=steps;i++){for(const lane of [inner,outer]){const p=pathAt(i/steps*PERIMETER,lane);vertices.push(p.x,.008,p.z);uvs.push(p.x/180,p.z/120)}}for(let i=0;i<steps;i++){const a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));g.setIndex(indices);g.computeVertexNormals();m.side=T.DoubleSide;const mesh=new T.Mesh(g,m);mesh.receiveShadow=true;world.add(mesh)}
function makeTexture(){const cv=document.createElement('canvas');cv.width=cv.height=256;const ctx=cv.getContext('2d');ctx.fillStyle='#a38964';ctx.fillRect(0,0,256,256);let seed=919;for(let i=0;i<9500;i++){seed=(seed*16807)%2147483647;const x=seed%256;seed=(seed*16807)%2147483647;const y=seed%256;ctx.fillStyle=i%2?'rgba(39,26,18,.13)':'rgba(239,220,181,.18)';ctx.fillRect(x,y,1.5,1)}const t=new T.CanvasTexture(cv);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(90,70);return t}
function buildCourse(){halos=[];if(world){scene.remove(world);disposeGroup(world)}world=new T.Group();scene.add(world);const field=mat(0x354b2d,.97),dirt=new T.MeshStandardMaterial({color:0xae9270,roughness:.96,map:makeTexture(),side:T.DoubleSide});const ground=new T.Mesh(new T.PlaneGeometry(700,700),field);ground.rotation.x=-Math.PI/2;ground.position.y=-.02;ground.receiveShadow=true;world.add(ground);trackRibbon(-1,15,dirt);trackRibbon(-2,-1,mat(0x7b815a));
 const railmat=mat(0xdddac9,.55);for(const lane of [-.7,15]){const points=[];for(let i=0;i<=240;i++){const p=pathAt(i/240*PERIMETER,lane);points.push(new T.Vector3(p.x,1.1,p.z))}const rail=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points,true),380,.043,4,true),railmat);world.add(rail);for(let i=0;i<96;i++){const p=pathAt(i/96*PERIMETER,lane);block(world,p.x,.55,p.z,.07,1.1,.07,railmat)}}
 const finish=pathAt(FINISH,5.5);block(world,finish.x,.018,finish.z,.20,.024,13,mat(0xf6eee0));
 for(const lane of [-1.7,13]){const p=pathAt(FINISH,lane);block(world,p.x,2.55,p.z,.20,5.1,.20,mat(0xe7e5dc));for(let j=0;j<7;j++)block(world,p.x,4.9-j*.30,p.z,.26,.27,.26,mat(j%2?0x18212c:0xeae9da));const sign=labelTexture('FINISH','#102131','#f5d487');const m=new T.Mesh(new T.PlaneGeometry(3.8,1.1),new T.MeshBasicMaterial({map:sign,side:T.DoubleSide}));m.position.set(p.x,5.5,p.z);m.rotation.y=Math.PI/2;world.add(m)}
 // Grandstand tiers behind the home straight; repeated seat blocks stay outside the course.
 for(const side of [-1,1]){for(let tier=0;tier<4;tier++){block(world,0,1.2+tier*.85,side*(R+62+tier*2),90,.7,3,mat(tier%2?0x34414a:0x52616a));for(let col=0;col<30;col++)block(world,-43+col*2.9,1.65+tier*.85,side*(R+62+tier*2),2.1,.25,.7,mat(col%3?0x6d7b7a:0xbeb8a6))}block(world,0,6.1,side*(R+68),97,.22,11,mat(0x374953))}
 for(let i=0;i<10;i++){const p=pathAt(i/10*PERIMETER,21);block(world,p.x,8,p.z,.13,16,.13,mat(0x69747a));block(world,p.x,16,p.z,2.3,.6,.4,mat(0xe7dfc4))}
 for(let i=0;i<48;i++){const at=pathAt(i/48*PERIMETER,29+(i%3)*3),height=3.3+(i%5)*.35;block(world,at.x,height*.43,at.z,.22,height*.86,.22,mat(0x4e3d2b));ell(world,at.x,height+1,at.z,1.6,height*.65,1.6,mat(i%2?0x263e31:0x36513a));}
 if(!haloTexture){const cv=document.createElement('canvas');cv.width=cv.height=64;const c=cv.getContext('2d'),g=c.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,244,190,.9)');g.addColorStop(.13,'rgba(255,218,136,.6)');g.addColorStop(.45,'rgba(255,212,119,.13)');g.addColorStop(1,'rgba(255,210,120,0)');c.fillStyle=g;c.fillRect(0,0,64,64);haloTexture=new T.CanvasTexture(cv)}
 if(!glowMaterial)glowMaterial=new T.MeshBasicMaterial({color:0xffe3ab,transparent:true,opacity:.8});
 for(let i=0;i<36;i++){const at=pathAt(i/36*PERIMETER,17.5);block(world,at.x,1.35,at.z,.09,2.7,.09,mat(0x546169));ell(world,at.x,2.8,at.z,.14,.20,.14,glowMaterial,false);const halo=new T.Sprite(new T.SpriteMaterial({map:haloTexture,transparent:true,opacity:.65,depthWrite:false,blending:T.AdditiveBlending}));halo.position.set(at.x,2.8,at.z);halo.scale.set(1.8,1.8,1.8);world.add(halo);halos.push(halo);}
 for(let i=0;i<10;i++){const at=pathAt(i/10*PERIMETER,21);block(world,at.x,15.95,at.z+.23,2.05,.4,.035,glowMaterial)}
 batchChildren(world);
}
function labelTexture(text,bg,fg){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,512,128);x.fillStyle=fg;x.textAlign='center';x.font='bold 70px sans-serif';x.fillText(text,256,90);return new T.CanvasTexture(c)}
function disposeGroup(g){const seen=new Set();g.traverse(o=>{if(o.geometry&&!Object.values(geo).includes(o.geometry)&&!seen.has(o.geometry)){seen.add(o.geometry);o.geometry.dispose()}if(o.material?.map&&o.material.map!==haloTexture)o.material.map.dispose()})}
function rebuild(rf){models.forEach(m=>{disposeGroup(m);herd.remove(m);m.userData.label.remove()});models=[];rf.horses.forEach(horse)}
function gateNumber(no){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#143e3b';ctx.fillRect(0,0,128,128);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 94px sans-serif';ctx.fillText(String(no),64,98);return new T.CanvasTexture(c)}
function buildGate(){
 if(gate){scene.remove(gate);disposeGroup(gate)}gate=new T.Group();doors=[];scene.add(gate);const n=models.length,step=gateSpan/n,steel=mat(0x344f57,.42,.5),pad=mat(0x216659,.8),bright=mat(0xf2eadd,.6),start=pathAt(START,0);gate.position.set(start.x,0,start.z);gate.rotation.y=-Math.atan2(start.tz,start.tx);
 const fix=new T.Group();gate.add(fix);for(let i=0;i<=n;i++){const z=(.5+i*step)*direction;for(const x of [-1.1,1.55])block(fix,x,1.35,z,.075,2.7,.06,steel,true);block(fix,.2,.92,z,2.65,.64,.05,pad,true);block(fix,.2,2.7,z,2.8,.10,.07,steel,true)}
 for(const x of [-1.1,1.6])block(fix,x,2.84,(.5+gateSpan/2)*direction,.15,.15,gateSpan+.22,steel,true);
 models.forEach((m,i)=>{const center=(.5+(i+.5)*step)*direction;const number=new T.Mesh(new T.PlaneGeometry(step*.78,.42),new T.MeshBasicMaterial({map:gateNumber(m.userData.h.horse),side:T.DoubleSide}));number.position.set(1.72,2.62,center);number.rotation.y=Math.PI/2;fix.add(number);
 for(const side of [-1,1]){const pivot=new T.Group();pivot.position.set(1.59,0,center+side*step*.46);gate.add(pivot);const width=step*.46,mid=-side*width/2;for(const y of [.63,1.1,1.65])block(pivot,0,y,mid,.055,.05,width,bright,true);for(let j=0;j<4;j++)block(pivot,0,1.15,-side*width*j/3,.045,1.02,.027,steel);doors.push({pivot,side})}
 });batchChildren(fix);
}
function relative(h,p){const a=(h.ranks||h.path||[]).map(Number);if(a.length<4)return +h.horse||1;const u=clamp(p/FINISH_AT,0,1)*3,i=Math.min(2,Math.floor(u)),f=u-i;return a[i]+(a[i+1]-a[i])*f}
function init(){host=document.getElementById('flowTrack');if(!host||!window.THREE)return;T=window.THREE;mode=3;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){fallback('3D非対応のため簡易表示');return}scene=new T.Scene();scene.background=new T.Color(0x899eaa);scene.fog=new T.Fog(0x899eaa,95,340);camera=new T.PerspectiveCamera(43,1,.1,650);renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;canvas=renderer.domElement;canvas.id='flow3dCanvas';canvas.setAttribute('aria-label','立体コースを走る予想馬群');canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fallback('3Dを停止しました。簡易表示に切替')});
 geo.sphere=new T.SphereGeometry(1,16,12);geo.box=new T.BoxGeometry(1,1,1);herd=new T.Group();scene.add(herd);hemi=new T.HemisphereLight(0xd8e8f3,0x5e4d37,2.0);scene.add(hemi);sun=new T.DirectionalLight(0xffdfb2,3.0);sun.position.set(-55,70,40);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-95;sun.shadow.camera.right=95;sun.shadow.camera.top=80;sun.shadow.camera.bottom=-80;sun.shadow.camera.far=240;sun.shadow.bias=-.0003;sun.shadow.normalBias=.03;scene.add(sun);scene.add(sun.target);
 labels=document.createElement('div');labels.className='r3-labels';ui=document.createElement('div');ui.className='r3-hud';ui.innerHTML='<div class="r3-racecard"><small>ODDS SCOPE · RACE THEATER</small><strong id="r3-racename">展開予想</strong><span id="r3-racedetail"></span></div><div class="r3-distance"><small>想定残り</small><b id="r3-remaining">—</b><span id="r3-pace"></span></div><div class="r3-top"><div><b>RACE FLOW <i>3D</i></b><span id="r3-stage">START</span></div><span id="r3-course">模式コース</span></div><div class="r3-bottom"><span id="r3-raceinfo">予想映像</span><b id="r3-finish"></b></div>';
 const controls=document.createElement('div');controls.className='r3-controls';controls.innerHTML='<button type="button" id="r3-camera">カメラ：中継</button><button type="button" id="r3-direction">右回り・模式</button>';controls.querySelector('#r3-camera').textContent='カメラ：'+['中継','追走','全景','横追走'][mode];controls.querySelector('#r3-camera').onclick=()=>{mode=(mode+1)%4;controls.querySelector('#r3-camera').textContent='カメラ：'+['中継','追走','全景','横追走'][mode];lastPaint=''};controls.querySelector('#r3-direction').onclick=()=>{directionOverride=directionOverride===null?-1:directionOverride===-1?1:null;lastPaint=''};
 const mood=document.createElement('button');mood.type='button';mood.id='r3-mood';mood.textContent='光：自動';mood.onclick=()=>{moodOverride=moodOverride===null?'sunset':moodOverride==='sunset'?'night':moodOverride==='night'?'day':null;lastPaint=''};controls.appendChild(mood);
 const play=document.createElement('button');play.type='button';play.className='r3-play';play.id='r3-play';play.textContent='▶ ゲートから再生';play.onclick=()=>window.playFlow?.();ui.appendChild(play);
 const views=document.createElement('div');views.className='r3-views';['中継','追走','全景','横追走'].forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.textContent=name;b.dataset.mode=i;b.onclick=()=>{mode=i;lastPaint='';controls.querySelector('#r3-camera').textContent='カメラ：'+name};views.appendChild(b)});ui.appendChild(views);
 const expand=document.createElement('button');expand.type='button';expand.className='r3-expand';expand.textContent='⛶ 拡大';expand.onclick=()=>{const expanded=host.classList.toggle('r3-expanded');expand.textContent=expanded?'✕ 閉じる':'⛶ 拡大';expand.setAttribute('aria-pressed',String(expanded));lastPaint=''};ui.appendChild(expand);
 const panel=document.querySelector('.flowControls');panel?.insertAdjacentElement('afterend',controls);attach();ready=true;document.documentElement.dataset.race3d='active';canvas.addEventListener('pointerdown',()=>{});window.__race3dDebug={version:'cinema-7'};loop(0);
}
function attach(){host=document.getElementById('flowTrack');if(host){host.appendChild(canvas);host.appendChild(labels);host.appendChild(ui)}}
function setAtmosphere(d){
 const iso=d.race?.start_iso;let hour=iso?Number(new Date(iso).toLocaleTimeString('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',hour12:false})):12;
 atmosphere=moodOverride||(hour>=18||hour<6?'night':hour>=16?'sunset':'day');
 const button=document.getElementById('r3-mood');if(button)button.textContent='光：'+({day:'昼景',sunset:'夕景',night:'ナイター'}[atmosphere])+(moodOverride?'':'（自動）');
 halos.forEach(o=>o.material.opacity=atmosphere==='night'?.8:atmosphere==='sunset'?.6:.12);if(skyKey===atmosphere)return;skyKey=atmosphere;const night=atmosphere==='night',sunset=atmosphere==='sunset';
 const cv=document.createElement('canvas');cv.width=16;cv.height=512;const c=cv.getContext('2d'),g=c.createLinearGradient(0,0,0,512);g.addColorStop(0,night?'#06162f':sunset?'#493d70':'#527f9d');g.addColorStop(.43,night?'#22466d':sunset?'#d47880':'#95b8c7');g.addColorStop(.51,night?'#597589':sunset?'#ffd49a':'#dae0ca');g.addColorStop(1,night?'#122a35':'#798064');c.fillStyle=g;c.fillRect(0,0,16,512);const tx=new T.CanvasTexture(cv);tx.mapping=T.EquirectangularReflectionMapping;tx.colorSpace=T.SRGBColorSpace;scene.background?.dispose?.();scene.background=tx;scene.fog.color.set(night?0x456278:sunset?0xba9989:0xb2c4c2);scene.fog.near=95;scene.fog.far=320;
 hemi.color.set(night?0xb0d2ff:sunset?0xf4c7ac:0xd8e8f3);hemi.groundColor.set(night?0x314651:0x6c5540);hemi.intensity=night?2.3:2.0;sun.color.set(night?0xcfe5ff:sunset?0xffb777:0xffdfb2);sun.intensity=night?2.7:sunset?3.2:3;sun.position.set(-55,sunset?25:70,40);renderer.toneMappingExposure=night?1.12:1.18;if(glowMaterial)glowMaterial.opacity=night?1:sunset?.9:.4;
}
// Venue direction is authoritative when the prediction payload omits course metadata.
const LEFT_NAR=/盛岡|浦和|船橋|川崎/;
const RIGHT_NAR=/門別|水沢|大井|金沢|笠松|名古屋|園田|姫路|高知|佐賀/;
function resolveDirection(d){
 const rf=d.race_flow||{},course=rf.course||{},race=d.race||{};
 const raw=[race.venue,race.track,race.course,race.racecourse,race.place,race.name,race.race_key,d.race_key].filter(v=>typeof v==='string').join(' ');
 if(LEFT_NAR.test(raw))return 1;
 if(RIGHT_NAR.test(raw))return -1;
 if(course.direction==='left'||course.direction==='左'||course.direction==='左回り')return 1;
 if(course.direction==='right'||course.direction==='右'||course.direction==='右回り')return -1;
 return null;
}
function render(d){ui.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.mode===mode)));const play=ui.querySelector('#r3-play');play.textContent=d.playing?'Ⅱ 一時停止':(+d.progress>=.995?'↻ もう一度再生':+d.progress>0?'▶ 続きから再生':'▶ ゲートから再生');play.classList.toggle('running',!!d.playing||+d.progress>0);
 if(lastRaceKey!==d.race_key){directionOverride=null;moodOverride=null;lastRaceKey=d.race_key}const rf=d.race_flow,t=clamp(+d.progress||0,0,1),rp=clamp((t-.08)/.92,0,1),p=(rp<.03?rp*rp/.06:rp-.015)/.985,w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;const key=JSON.stringify(rf.horses.map(h=>[h.horse,h.frame,h.name]));if(key!==sourceKey){rebuild(rf);sourceKey=key}
 setAtmosphere(d);const verifiedDirection=resolveDirection(d),dir=directionOverride??verifiedDirection??-1,ck=dir+':'+(rf.course?.surface||'dirt');if(ck!==courseKey){direction=dir;buildCourse();courseKey=ck}
 const gk=key+':'+dir;if(gk!==gateKey){buildGate();gateKey=gk}const gateOpen=clamp((t-.045)/.025,0,1);doors.forEach(({pivot,side})=>pivot.rotation.y=-side*gateOpen*Math.PI*.49);
 const cameraButton=document.getElementById('r3-direction');if(cameraButton)cameraButton.textContent=directionOverride!==null?(direction===-1?'右回り':'左回り')+'（手動）':rf.course?.direction?(direction===-1?'右回り':'左回り')+'（自動）':'方向未取得（仮表示）';
 if(canvas.width!==Math.floor(w*renderer.getPixelRatio())||canvas.height!==Math.floor(h*renderer.getPixelRatio()))renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=w<h?54:42;camera.updateProjectionMatrix();
 models.forEach(m=>{m.userData.h=rf.horses.find(h=>+h.horse===+m.userData.h.horse)||m.userData.h});
 const ranks=models.map(m=>({m,pos:relative(m.userData.h,p)})).sort((a,b)=>a.pos-b.pos||+a.m.userData.h.horse-+b.m.userData.h.horse),best=ranks[0]?.pos||1;
 const finalOrder=models.map(m=>({m,pos:relative(m.userData.h,1)})).sort((a,b)=>a.pos-b.pos||+a.m.userData.h.horse-+b.m.userData.h.horse),finalLanes=[-3,-3,-3,-3];let finalGap=0;for(const {m,pos} of finalOrder){const lane=m.userData.index%4,gap=Math.max((pos-finalOrder[0].pos)*1.15,finalLanes[lane]+2.65);finalLanes[lane]=gap;finalGap=Math.max(finalGap,gap)}
 const leadDistance=p<=FINISH_AT?(p-FINISH_AT)*TRAVEL:(p-FINISH_AT)/(1-FINISH_AT)*(finalGap+1);
 let finished=0;const positions=[],laneGaps=[-3,-3,-3,-3];
 for(const {m,pos} of ranks){const u=m.userData,index=u.index,merge=clamp((p-.035)/.14,0,1),blend=merge*merge*(3-2*merge),stall=.5+(index+.5)*gateSpan/models.length,lane=stall*(1-blend)+(1.3+(index%4)*2.1+.25*Math.sin(p*Math.PI)*Math.sin(index))*blend,gap=Math.max((pos-best)*1.15,laneGaps[index%4]+2.65),dist=FINISH+leadDistance-gap*blend;laneGaps[index%4]=gap;u.distance=dist;const at=pathAt(dist,lane),phase=p*72*Math.PI*2+index*.9;u.body.position.y=Math.sin(phase*2)*.025;u.body.rotation.x=Math.sin(phase)*.018;m.position.set(at.x,.01,at.z);m.rotation.y=-Math.atan2(at.tz,at.tx);u.body.rotation.z=Math.sin(phase)*.018;u.rider.rotation.z=Math.sin(phase+.7)*.045;u.tail.rotation.x=Math.sin(phase*.45)*.11;u.ring.visible=+d.selected===+u.h.horse;
 for(const leg of u.legs){const f=phase+(leg.hind?2.0:0)+(leg.side>0?.65:0);leg.upper.rotation.z=Math.sin(f)*.58+(leg.hind?.12:-.08);leg.knee.rotation.z=(leg.hind?-1:1)*(.13+Math.max(0,Math.sin(f-.6))*.9)}
 if(p===0){u.body.position.y=-.18;u.body.rotation.set(0,0,0);u.rider.rotation.z=0;u.tail.rotation.x=0;u.legs.forEach(l=>{l.upper.rotation.z=0;l.knee.rotation.z=0})}if(dist>=FINISH)finished++;positions.push(m.position);}
 const center=new T.Vector3();positions.forEach(v=>center.add(v));center.divideScalar(Math.max(1,positions.length));const lead=ranks[0]?.m,focus=models.find(m=>+m.userData.h.horse===+d.selected)||lead;const leadAt=pathAt(lead?.userData.distance||FINISH,0),tangent=new T.Vector3(leadAt.tx,0,leadAt.tz),outward=new T.Vector3(-leadAt.tz,0,leadAt.tx),look=center.clone().add(new T.Vector3(0,.9,0));
 if(mode===3){const f=focus.position.clone(),at=pathAt(focus.userData.distance,0),side=new T.Vector3(-at.tz,0,at.tx),forward=new T.Vector3(at.tx,0,at.tz);camera.position.copy(f).addScaledVector(side,w<h?12:17).addScaledVector(forward,2.4).add(new T.Vector3(0,3.15,0));camera.lookAt(f.addScaledVector(forward,1.8).add(new T.Vector3(0,1.2,0)))}else if(mode===2){camera.position.copy(center).addScaledVector(outward,22).add(new T.Vector3(0,43,0));camera.lookAt(look)}else if(mode===1){const f=focus.position.clone();camera.position.copy(f).addScaledVector(tangent,-10).addScaledVector(outward,11).add(new T.Vector3(0,7,0));camera.lookAt(f.lerp(center,.45).add(new T.Vector3(0,1.25,0)))}else{
  const spread=Math.max(12,...positions.map(v=>v.distanceTo(center)*2)),distance=(w<h?1.32:1.05)*spread+6;camera.position.copy(center).addScaledVector(outward,distance).addScaledVector(tangent,-distance*(w<h?.65:.35)).add(new T.Vector3(0,8+spread*.25,0));camera.lookAt(look);
 }
 if(t<.16&&mode!==2){const gateAt=pathAt(START,7.5),gcenter=new T.Vector3(gateAt.x,1.2,gateAt.z),gpos=gcenter.clone().addScaledVector(tangent,14).addScaledVector(outward,9).add(new T.Vector3(0,6,0)),blend=clamp((t-.10)/.06,0,1);camera.position.lerp(gpos,1-blend);camera.lookAt(look.clone().lerp(gcenter,1-blend))}
 renderer.render(scene,camera);const occupied=[];for(const {m} of ranks){const u=m.userData,v=new T.Vector3(0,2.45,0).applyMatrix4(m.matrixWorld).project(camera),x=(v.x*.5+.5)*w,y=(-v.y*.5+.5)*h,active=+d.selected===+u.h.horse;const inFrame=v.z<1&&x>12&&x<w-12&&y>60&&y<h-42;u.label.hidden=t<.10||!inFrame||mode===3||(mode===1&&m!==focus&&m.position.distanceTo(focus.position)>11);let lx=x,ly=y;for(const [dx,dy] of [[0,0],[-18,-26],[18,-26],[-32,-52],[0,-52],[32,-52],[-18,-78],[18,-78],[0,-104]]){const cx=clamp(x+dx,16,w-16),cy=Math.max(105,y+dy);lx=cx;ly=cy;if(!occupied.some(o=>Math.abs(o.x-cx)<28&&Math.abs(o.y-cy)<27))break}occupied.push({x:lx,y:ly});u.label.style.setProperty('--stem',Math.max(0,y-ly)+'px');u.label.style.transform=`translate(${lx}px,${ly}px) translate(-50%,-100%)`;u.label.classList.toggle('selected',active);u.label.title=u.h.horse+'番 '+(u.h.name||'');}
 const stage=t<.045?'ゲート内・発走準備':t<.08?'ゲート開放':p>=FINISH_AT?'ゴール前':p<.18?'スタート':p<.48?'向正面':p<.76?'コーナー':'最後の直線';ui.querySelector('#r3-stage').textContent=(finished===models.length?'全頭ゴール':stage)+(mode===3?' · 注目 '+focus.userData.h.horse+'番':'');
 ui.querySelector('#r3-finish').textContent=finished?`ゴール通過 ${finished} / ${models.length}頭`:'';ui.querySelector('#r3-course').textContent=(rf.course?.distance?rf.course.distance+'m · ':'')+'コース形状は模式';ui.querySelector('#r3-raceinfo').textContent='予想映像 / 模式コース';const race=d.race||{};ui.querySelector('#r3-racename').textContent=race.baba_name&&race.race?race.baba_name+' '+race.race+'R':'展開シミュレーション';const start=race.start_iso?new Date(race.start_iso).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'}):'';ui.querySelector('#r3-racedetail').textContent=[start?start+' 発走':'',rf.course?.distance?rf.course.distance+'m':'',direction===-1?'右回り':'左回り'].filter(Boolean).join(' · ');ui.querySelector('#r3-remaining').textContent=rf.course?.distance?Math.max(0,Math.round(rf.course.distance*(1-clamp(p/FINISH_AT,0,1))/10)*10)+'m':'—';ui.querySelector('#r3-pace').textContent=rf.label||rf.pace||'想定ペース';
 window.__race3dDebug={version:'cinema-7',horses:models.length,finished,progress:t,raceProgress:p,gateOpen,gateStalls:models.length,start:START,direction,mode,atmosphere,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,positions:models.map(m=>({horse:+m.userData.h.horse,distance:m.userData.distance,x:m.position.x,z:m.position.z})),finish:FINISH};
}
function loop(now){if(disposed)return;raf=requestAnimationFrame(loop);const d=window.__oddsRace3dData;if(!ready||document.hidden||!d?.race_flow?.horses?.length){if(canvas)canvas.style.visibility='hidden';if(labels)labels.style.visibility='hidden';if(ui)ui.style.visibility='hidden';return}if(!canvas.isConnected)attach();canvas.style.visibility='';labels.style.visibility='';ui.style.visibility='';const r=host.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const paint=[d.playing,d.progress,d.selected,d.race_key,mode,directionOverride,moodOverride,d.race?.start_iso,host.clientWidth,host.clientHeight,JSON.stringify([d.race_flow.course,d.race_flow.horses.map(h=>[h.horse,h.frame,h.name,h.path,h.ranks])])].join('|');if(paint===lastPaint)return;lastPaint=paint;try{render(d)}catch(e){console.error('Race3D render',e);fallback('3D描画に失敗したため簡易表示')}}
function fallback(text){document.documentElement.dataset.race3d='fallback';if(canvas)canvas.style.display='none';if(labels)labels.style.display='none';if(ui)ui.style.display='none';ready=false;cancelAnimationFrame(raf);const el=document.getElementById('flowNote');if(el)el.textContent=text+'。 '+el.textContent}
function boot(){if(loading||ready||!document.getElementById('flowTrack'))return;loading=true;const script=document.createElement('script');script.src='/assets/three.min.js?v=158';script.onload=()=>init();script.onerror=()=>fallback('3Dライブラリを読み込めません');document.head.appendChild(script)}
window.addEventListener('pagehide',e=>{cancelAnimationFrame(raf);if(!e.persisted){disposed=true;renderer?.dispose()}});window.addEventListener('pageshow',e=>{if(e.persisted&&ready&&!disposed){lastPaint='';cancelAnimationFrame(raf);loop(0)}});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
