/* ODDS SCOPE NAR — WebGL race flow. Procedural 3D; no external model assets. */
(function(){
let three=null,scene,camera,renderer,group,models=[],raf=0,canvas=null,host=null,ready=false,playing=false,progress=0,lastTime=0,source=null;
const palette=[0xf1f2f4,0x22252b,0xe34250,0x276bd0,0xf1d338,0x25a864,0xe47b25,0xe17bb3];
const material=(color,roughness=.83)=>new three.MeshStandardMaterial({color,roughness,metalness:.06});
function box(w,h,d,mat){let m=new three.Mesh(new three.BoxGeometry(w,h,d),mat);m.castShadow=true;m.receiveShadow=true;return m}
function ellipsoid(x,y,z,a,b,c,mat,parent){let m=new three.Mesh(new three.SphereGeometry(1,12,9),mat);m.position.set(x,y,z);m.scale.set(a,b,c);m.castShadow=true;parent.add(m);return m}
function horse(h,i){let root=new three.Group(),coat=material([0x51352a,0x352820,0x6c4732,0x2d2423,0x74543c][i%5]),dark=material(0x211c1b),silk=material(palette[Math.max(0,Math.min(7,(+h.frame||1)-1))]),skin=material(0xd7a47c),saddle=material(0x1b252e);
ellipsoid(0,1.13,0,.66,.31,.26,coat,root);let neck=ellipsoid(.49,1.41,0,.21,.44,.20,coat,root);neck.rotation.z=-.46;ellipsoid(.73,1.75,0,.29,.19,.17,coat,root);ellipsoid(.96,1.68,0,.20,.11,.14,dark,root);
for(let side of [-1,1]){let ear=ellipsoid(.61,1.96,side*.12,.055,.14,.05,coat,root);ear.rotation.z=-.24;ellipsoid(.79,1.78,side*.158,.023,.025,.016,dark,root)}
let tail=ellipsoid(-.74,1.2,0,.34,.075,.09,dark,root);tail.rotation.z=-.42;
let legs=[];for(let x of [-.40,.37])for(let z of [-.16,.16]){let upper=new three.Group();upper.position.set(x,.99,z);root.add(upper);let thigh=ellipsoid(0,-.22,0,.105,.29,.09,coat,upper),lower=new three.Group();lower.position.y=-.45;upper.add(lower);ellipsoid(0,-.24,0,.064,.26,.061,coat,lower);let hoof=box(.17,.10,.17,dark);hoof.position.set(.065,-.49,0);lower.add(hoof);legs.push({upper,lower,front:x>0,side:z>0?1:-1})}
let rider=new three.Group();rider.position.set(-.08,1.57,0);root.add(rider);let torso=ellipsoid(.05,.28,0,.21,.34,.19,silk,rider);torso.rotation.z=-.55;ellipsoid(.22,.55,0,.105,.12,.105,skin,rider);ellipsoid(.22,.66,0,.14,.085,.14,silk,rider);
for(let z of [-.17,.17]){let arm=ellipsoid(.27,.26,z,.075,.25,.07,silk,rider);arm.rotation.z=-.75;let boot=ellipsoid(-.18,-.20,z,.10,.25,.085,dark,rider);boot.rotation.z=.4}
let cloth=box(.43,.045,.40,saddle);cloth.position.set(-.13,1.45,0);root.add(cloth);
root.userData={h,legs,base:0};group.add(root);models.push(root)}
function build(rf){models.forEach(m=>group.remove(m));models=[];let horses=rf?.horses||[];horses.forEach(horse);source=rf}
function init(){host=document.getElementById('flowTrack');if(!host||!window.THREE)return false;three=window.THREE;scene=new three.Scene();scene.background=new three.Color(0x8bacc0);scene.fog=new three.FogExp2(0x9bb0b6,.016);camera=new three.PerspectiveCamera(43,1,.1,240);renderer=new three.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=three.PCFSoftShadowMap;renderer.outputColorSpace=three.SRGBColorSpace;canvas=renderer.domElement;canvas.id='flow3dCanvas';canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;display:block;z-index:1;';host.style.position='relative';host.appendChild(canvas);
scene.add(new three.HemisphereLight(0xe3f2ff,0x6e553f,2));let sun=new three.DirectionalLight(0xffe4ba,2.5);sun.position.set(-12,24,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;scene.add(sun);
let ground=new three.Mesh(new three.PlaneGeometry(260,180),material(0x85613e));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
for(let z of [-8,9]){let rail=box(220,.12,.10,material(0xe5e6df));rail.position.set(0,1.1,z);scene.add(rail);for(let x=-90;x<100;x+=4){let post=box(.09,1.1,.09,material(0xd6d8d0));post.position.set(x,.56,z);scene.add(post)}}
let line=box(.23,.012,17,material(0xf5eee1));line.position.set(20,.014,.5);scene.add(line);
let pole=box(.20,5,.20,material(0xf4f4ef));pole.position.set(20,2.5,-8.5);scene.add(pole);
for(let i=0;i<8;i++)for(let j=0;j<2;j++){let tile=box(.42,.42,.03,material((i+j)%2?0x1d2227:0xf5f5ef));tile.position.set(20+j*.42,4.7-i*.42,-8.5);scene.add(tile)}
group=new three.Group();scene.add(group);ready=true;return true}
function update(rf,p,t){if(!ready)return;if(rf!==source)build(rf);progress=p;let n=models.length;if(!n)return;let ranks=models.map(m=>({m,pos:window.flowInterp?window.flowInterp(m.userData.h,p):(+m.userData.h?.ranks?.[3]||n)}));let best=Math.min(...ranks.map(x=>x.pos));for(let {m,pos} of ranks){let h=m.userData.h,no=+h.horse||0,lane=(no*7+(+h.frame||1)*3)%7;let target=20-(pos-best)*1.65-(1-p)*7;let z=-5+lane*1.5+Math.sin(p*Math.PI*2+no*.7)*Math.sin(p*Math.PI)*.55;m.position.set(target,.015,z);m.rotation.y=-.035+Math.sin(p*5+no)*.02;let phase=t*.012+no*.7;m.position.y=.04+Math.abs(Math.sin(phase))*.055;for(let leg of m.userData.legs){let v=phase+(leg.front?0:Math.PI)+(leg.side>0?Math.PI*.58:0);leg.upper.rotation.z=Math.sin(v)*.63;leg.lower.rotation.z=.2+Math.max(0,Math.sin(v+1.1))*.85}}
let leader=ranks.sort((a,b)=>a.pos-b.pos)[0]?.m;let lx=leader?.position.x||10;camera.position.set(lx-10,5.2,17);camera.lookAt(lx+3,1.15,0);let w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}renderer.render(scene,camera)}
function loop(t){raf=requestAnimationFrame(loop);let rf=window.last?.race_flow;if(!rf?.horses?.length||!host?.isConnected)return;let p=typeof window.flowProgress==='number'?window.flowProgress:progress;update(rf,p,t)}
function boot(){if(ready)return;let hostEl=document.getElementById('flowTrack');if(!hostEl)return;if(!window.THREE){let script=document.createElement('script');script.src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r160/three.min.js';script.onload=()=>{if(init())loop(0)};script.onerror=()=>{};document.head.appendChild(script)}else if(init())loop(0)}
const observer=new MutationObserver(()=>{let target=document.getElementById('flowTrack');if(target&&target.querySelector('#flowCanvas')){if(!ready)boot();else if(!document.getElementById('flow3dCanvas')){host=target;host.appendChild(canvas)}}});observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();