services:
  - type: web
    name: potun-auto
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 4 --timeout 60 app:app
